### ISSUE TITLE
Include intended audience in README.md

### ISSUE THREAD

**Issue by Queeniebee** [leobalter/hanoi#1]
After reading through `README.md`, not clear if the exercise is for people completely new to Test Driven Development or people who are familiar with the concept and want an intermediate exercise.

**Comment by leobalter** [comment]
I'm sorry for this super long delay. This exercise is meant for both new and experienced developers.

New developers can learn **how to code** from TDD (that's an extra), and experienced developers can practice one golden rule on testing: baby steps.

Surprisingly, new developers, the less experienced ones use to provide more great ideas than experienced developers. There are places that run the Coding Dojo weekly and this is a well known fact.

I should probably update the repo with the basics for coding dojo and use other branches to register exercises.
